version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 539247488585.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Ejecucion de pruebas unitarias
      - pytest --cov-fail-under=100 --cov=src
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t listanegra2 .
      - docker tag listanegra2:latest 539247488585.dkr.ecr.sa-east-1.amazonaws.com/listanegra2:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 539247488585.dkr.ecr.sa-east-1.amazonaws.com/listanegra2:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"app-entrega4-2","imageUri":"539247488585.dkr.ecr.sa-east-1.amazonaws.com/listanegra2:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"539247488585.dkr.ecr.sa-east-1.amazonaws.com/listanegra2:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
